[build]
target = "x86_64-unknown-linux-musl"

[target.aarch64-unknown-linux-musl]
linker = "clang"

[target.x86_64-unknown-linux-musl]
linker = "clang"

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin20.4-clang"
ar = "x86_64-apple-darwin20.4-ar"

[target.aarch64-apple-darwin]
linker = "arm64-apple-darwin20.4-clang"
ar = "arm64-apple-darwin20.4-ar"
